# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'Runner' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Runner
    pod 'FBSDKCoreKit', '4.39.1'
    pod 'FBSDKLoginKit', '4.39.1'
end

pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'